server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_eatery
    username: root
    password: ms128411
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.eatery.cd.pojo

logging:
  level:
    com:
      eatery: debug
